Repository nextcloud/ldap_contacts_backend, pull requests merged in 2023-12, with the labels that each got.

#101 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review, feedback-requested

#98 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#100 Create initial README.md
  README.md
Labels: 3. to review, feedback-requested

#102 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review, feedback-requested

#107 Release for 28
  appinfo/info.xml
Labels: 3. to review

#108 Add psalm
  .github/workflows/psalm.yml
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Controller/ContactsController.php
  lib/Model/Configuration.php
  lib/Service/Configuration.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/generate-stub.sh
  tests/stubs/stub.phpstub
Labels: 3. to review
