Repository nextcloud/ldap_contacts_backend, pull requests merged in 2023-03, with the labels that each got.

#69 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#70 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#65 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#73 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#74 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#75 update composer config and dev deps
  .nextcloudignore
  composer.json
  composer.lock
  lib/Command/Add.php
  lib/Controller/ContactsController.php
  lib/Http/InlineImageResponse.php
  lib/Model/Card.php
  lib/Provider/ImportProvider.php
  lib/Service/AddressBook.php
  lib/Service/AddressBookProvider.php
  lib/Service/ConnectionImporter.php
  lib/Service/ContactsAddressBookFactory.php
  lib/Service/LdapQuerent.php
  lib/Service/PhotoService.php
Labels: backport-request, 3. to review, technical debt

#71 chore(CI): Adjust testing matrix for Nextcloud 26 on stable26
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 4. to release

#72 chore: Add Nextcloud 27 support on master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/update-nextcloud-ocp.yml
  appinfo/info.xml
Labels: 4. to release

#80 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#81 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#79 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#78 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#83 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#82 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
