Repository nextcloud/ldap_contacts_backend, pull requests merged in 2024-08, with the labels that each got.

#188 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#189 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#193 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#173 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#181 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#187 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#190 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
