Repository nextcloud/ldap_contacts_backend, pull requests merged in 2024-12, with the labels that each got.

#233 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#235 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#236 chore(deps): composer require --dev nextcloud/ocp:dev-master -W
  composer.lock
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.lock
  vendor-bin/rector/composer.lock
Labels: dependencies, 4. to release

#237 chore(deps): composer require --dev nextcloud/ocp:dev-stable30 -W
  composer.lock
Labels: dependencies, 4. to release

#238 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#239 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#240 Add reuse compliance
  .github/CODEOWNERS
  .github/workflows/reuse.yml
  .gitignore
  .nextcloudignore
  .php-cs-fixer.dist.php
  AUTHORS.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  REUSE.toml
  appinfo/info.xml
  appinfo/routes.php
  img/app-dark.svg
  img/app.svg
  krankerl.toml
  lib/AppInfo/Application.php
  lib/Command/Add.php
  lib/Command/Delete.php
  lib/Command/Edit.php
  lib/Command/ListConfigs.php
  lib/Command/TConfigurationDetail.php
  lib/Controller/ContactsController.php
  lib/Exception/ConfigurationNotFound.php
  lib/Exception/InvalidConfiguration.php
  lib/Exception/PhotoServiceUnavailable.php
  lib/Exception/RecordNotFound.php
  lib/Http/InlineImageResponse.php
  lib/Model/Card.php
  lib/Model/Configuration.php
  lib/Model/LDAPBaseConfiguration.php
  lib/Provider/ImportProvider.php
  lib/Service/AddressBook.php
  lib/Service/AddressBookProvider.php
  lib/Service/Configuration.php
  lib/Service/ConnectionImporter.php
  lib/Service/ContactsAddressBook.php
  lib/Service/ContactsAddressBookFactory.php
  lib/Service/ICardBackend.php
  lib/Service/LdapCardBackend.php
  lib/Service/LdapEntryToVcard.php
  lib/Service/LdapQuerent.php
  lib/Service/LdapQuerentFactory.php
  lib/Service/PhotoService.php
  psalm.xml
  screenshots/contactsmenu-with-action.png.license
  tests/Service/ConfigurationTest.php
  tests/bootstrap.php
  tests/phpunit.xml
  tests/psalm-baseline.xml
  tests/stubs/generate-stub.sh
  tests/stubs/stub.phpstub
Labels: documentation, 3. to review

#241 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#242 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
