Repository nextcloud/ldap_contacts_backend, pull requests merged in 2024-01, with the labels that each got.

#112 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#120 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#123 [stable27] Update workflows for selfhosted runners support
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: backport-request, 3. to review

#125 [stable26] Update workflows for selfhosted runners support
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#124 Update composer dependencies
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
  composer.lock
  lib/Http/InlineImageResponse.php
Labels: 3. to review

#118 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#128 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#126 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#129 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
