Repository nextcloud/ldap_contacts_backend, pull requests merged in 2024-02, with the labels that each got.

#131 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#133 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#136 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#139 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#134 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#135 [stable28] chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#140 chore: Fix dependencies and platform for ocp updates
  composer.json
  composer.lock
Labels: 4. to release
