Repository nextcloud/ldap_contacts_backend, pull requests merged in 2025-02, with the labels that each got.

#252 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#251 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#244 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#253 chore: Bump version to 1.11.0
  appinfo/info.xml
Labels: 4. to release
